## v0.7.0
* Now, when values or actions do not exist, error message now shows the list of values/actions available to better hint at what might have went wrong.
* Now, when a value getter causes an error to be thrown, it will be stored away so that other value getters can run. Then, it will be thrown when attempting to retrieve the value via `.get(...)`. Before this fix, upon encountering scenarios like this, an incorrect error would be thrown, claiming that certain value keys do not exist when in reality they just could not execute because a preceding getter has caused an error.
